version: '3'

services:

  python:
    image: python:3.8.12-bullseye
    volumes:
    - .:/picSTy:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    links:
    - golang

  golang:
    image: golang:1.16
    volumes:
    - .:/picSTy:cached
    command: /bin/sh -c "while sleep 1000; do :; done"

